export const dummyData = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2024-01-15',
  },
  {
    id: 2,
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-03-22',
  },
  {
    id: 3,
    name: 'Carol White',
    email: 'carol@example.com',
    role: 'Viewer',
    status: 'Inactive',
    joinDate: '2024-05-10',
  },
  {
    id: 4,
    name: 'David Brown',
    email: 'david@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-07-01',
  },
  {
    id: 5,
    name: 'Emma Davis',
    email: 'emma@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2024-09-18',
  },
  {
    id: 6,
    name: 'Frank Wilson',
    email: 'frank@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2023-11-05',
  },
  {
    id: 7,
    name: 'Grace Lee',
    email: 'grace@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-02-28',
  },
  {
    id: 8,
    name: 'Henry Taylor',
    email: 'henry@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-08-12',
  },
  {
    id: 9,
    name: 'Ivy Martinez',
    email: 'ivy@example.com',
    role: 'Viewer',
    status: 'Inactive',
    joinDate: '2025-01-20',
  },
  {
    id: 10,
    name: 'Jack Anderson',
    email: 'jack@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-06-14',
  },
  {
    id: 11,
    name: 'Kara Thomas',
    email: 'kara@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-12-03',
  },
  {
    id: 12,
    name: 'Leo Garcia',
    email: 'leo@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2024-10-09',
  },
  {
    id: 13,
    name: 'Mia Rodriguez',
    email: 'mia@example.com',
    role: 'Editor',
    status: 'Inactive',
    joinDate: '2024-04-17',
  },
  {
    id: 14,
    name: 'Noah Hernandez',
    email: 'noah@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-09-30',
  },
  {
    id: 15,
    name: 'Olivia Lopez',
    email: 'olivia@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2025-02-11',
  },
  {
    id: 16,
    name: 'Paul Hill',
    email: 'paul@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-08-25',
  },
  {
    id: 17,
    name: 'Quinn Allen',
    email: 'quinn@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-10-18',
  },
  {
    id: 18,
    name: 'Riley Young',
    email: 'riley@example.com',
    role: 'Viewer',
    status: 'Inactive',
    joinDate: '2024-11-02',
  },
  {
    id: 19,
    name: 'Sophia King',
    email: 'sophia@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-05-06',
  },
  {
    id: 20,
    name: 'Tyler Wright',
    email: 'tyler@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-07-22',
  },
  {
    id: 21,
    name: 'Uma Scott',
    email: 'uma@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2025-03-14',
  },
  {
    id: 22,
    name: 'Victor Green',
    email: 'victor@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-01-29',
  },
  {
    id: 23,
    name: 'Willow Adams',
    email: 'willow@example.com',
    role: 'Admin',
    status: 'Inactive',
    joinDate: '2023-06-15',
  },
  {
    id: 24,
    name: 'Xander Baker',
    email: 'xander@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2024-12-07',
  },
  {
    id: 25,
    name: 'Yara Carter',
    email: 'yara@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-09-01',
  },
  {
    id: 26,
    name: 'Zane Perez',
    email: 'zane@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-11-19',
  },
  {
    id: 27,
    name: 'Ava Mitchell',
    email: 'ava@example.com',
    role: 'Viewer',
    status: 'Inactive',
    joinDate: '2025-01-08',
  },
  {
    id: 28,
    name: 'Ben Roberts',
    email: 'ben@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-07-18',
  },
  {
    id: 29,
    name: 'Chloe Turner',
    email: 'chloe@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-05-04',
  },
  {
    id: 30,
    name: 'Dylan Phillips',
    email: 'dylan@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2024-10-22',
  },
  {
    id: 31,
    name: 'Eva Campbell',
    email: 'eva@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-03-11',
  },
  {
    id: 32,
    name: 'Finn Parker',
    email: 'finn@example.com',
    role: 'Admin',
    status: 'Inactive',
    joinDate: '2023-08-09',
  },
  {
    id: 33,
    name: 'Gemma Evans',
    email: 'gemma@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2025-02-25',
  },
  {
    id: 34,
    name: 'Hank Edwards',
    email: 'hank@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-06-30',
  },
  {
    id: 35,
    name: 'Isla Collins',
    email: 'isla@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-12-16',
  },
  {
    id: 36,
    name: 'Jude Stewart',
    email: 'jude@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2024-11-28',
  },
  {
    id: 37,
    name: 'Kylie Morris',
    email: 'kylie@example.com',
    role: 'Editor',
    status: 'Inactive',
    joinDate: '2024-04-05',
  },
  {
    id: 38,
    name: 'Liam Rogers',
    email: 'liam@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-09-21',
  },
  {
    id: 39,
    name: 'Maya Reed',
    email: 'maya@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2025-03-01',
  },
  {
    id: 40,
    name: 'Nathan Cook',
    email: 'nathan@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-08-14',
  },
  {
    id: 41,
    name: 'Nora Bell',
    email: 'nora@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-10-07',
  },
  {
    id: 42,
    name: 'Oscar Murphy',
    email: 'oscar@example.com',
    role: 'Viewer',
    status: 'Inactive',
    joinDate: '2024-12-20',
  },
  {
    id: 43,
    name: 'Penny Rivera',
    email: 'penny@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-05-23',
  },
  {
    id: 44,
    name: 'Quinn Cooper',
    email: 'quinn2@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-07-08',
  },
  {
    id: 45,
    name: 'Ryan Cox',
    email: 'ryan@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2025-02-04',
  },
  {
    id: 46,
    name: 'Sienna Ward',
    email: 'sienna@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-01-12',
  },
  {
    id: 47,
    name: 'Theo Gray',
    email: 'theo@example.com',
    role: 'Admin',
    status: 'Inactive',
    joinDate: '2023-06-27',
  },
  {
    id: 48,
    name: 'Violet Ramos',
    email: 'violet@example.com',
    role: 'Viewer',
    status: 'Active',
    joinDate: '2024-11-15',
  },
  {
    id: 49,
    name: 'Wyatt Kim',
    email: 'wyatt@example.com',
    role: 'Editor',
    status: 'Active',
    joinDate: '2024-09-09',
  },
  {
    id: 50,
    name: 'Zoe Foster',
    email: 'zoe@example.com',
    role: 'Admin',
    status: 'Active',
    joinDate: '2023-11-30',
  },
];
